---

language: node_js

node_js: lts/*

script:
  - npm run lint
  - npm run test

deploy:
  provider: script
  skip_cleanup: true
  script: npm run release
  on:
    repo: system76/renovate-config
    branch: master
